alias gb='git branch'
alias gba='git branch --all'
alias gc='git commit'
alias gcp='git cherry-pick --ff'
alias gf='git fetch --prune origin'
alias gl='git pull'
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gpmr='git push origin --set-upstream HEAD --push-option=merge_request.create --push-option=merge_request.remove_source_branch'
alias gr='git rebase'
alias gri='git rebase --interactive'
alias gs='git stash'
alias gsp='git stash pop'
alias gst='git status --short --branch'

alias ts='tig status'
